### ISSUE TITLE
Border Color Inconsistent on Symlinked Plugins

### ISSUE THREAD

**Issue by danielwrobert** [nielslange/smntcs-show-symlinked-plugins#2]
A handful of symlinked plugins seem to not getting any border applied.

One common denominator seems to be that they are all Inactive. However, not _all_ Inactive plugins appear to be affected.

### Screenshots

![CleanShot 2023-05-15 at 14 54 06@2x](https://github.com/nielslange/smntcs-show-symlinked-plugins/assets/481776/8eebddd8-d823-4b53-a576-bebc4845b0ec)

![Screen Shot 2023-05-16 at 02 24 22](https://github.com/nielslange/smntcs-show-symlinked-plugins/assets/481776/d300c433-9c55-4bc1-b93f-ac3a63690eed)

**Comment by nielslange** [comment]
Thanks for reporting this issue in this repo, @danielwrobert. @roykho and I applied some changes to the plugin yesterday. While we haven't looked into this particular issue, would you mind checking out the most recent version of the plugin to see if the problem still exists?

The function that detects symlinked plugins is defined in https://github.com/nielslange/smntcs-show-symlinked-plugins/blob/e8b0d37a475fe90f0f9783364ef0adea915b2548/smntcs-show-symlinked-plugins.php#L48-L49

If the problem still occurs on your end, would you mind debugging this part to check if you see anything suspicious there?

**Comment by roykho** [comment]
Hmmm strange indeed. For me, its picking up all the symlinked plugins. ![](https://d.pr/i/HYemJ6+)

**Comment by danielwrobert** [comment]
Seems to be capturing all of them now, as of 4294f98. I'll close this out. Thanks!

**Comment by nielslange** [comment]
> Seems to be capturing all of them now, as of [4294f98](https://github.com/nielslange/smntcs-show-symlinked-plugins/commit/4294f98370dc8ca04916374fa7b39b2fd0ea6a90). I'll close this out. Thanks!

@danielwrobert I'm glad to hear that it's resolved. In [4294f98](https://github.com/nielslange/smntcs-show-symlinked-plugins/commit/4294f98370dc8ca04916374fa7b39b2fd0ea6a90), I changed from the plugin textdomain, e.g. `shipping-workshop.php` towards the plugin file, e.g. `shipping-workshop-dry-run/shipping-workshop.php`. That said, it's still strange why you saw the initial result, as I cannot imagine that your symlinked plugins were actually using the same textdomain. On the other hand, glad the issue is solved and if you see any potential improvements, just let me know. 🙌
